name: tests-auth

on:
  push:
    paths:
      - "auth/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: cd auth && npm install && npm run test:ci
